import { Ce } from './domHelpers.js';
import { buildStoryExportFileName } from './fileIoHelpers.js';
import { getVietnameseLabel } from './vietnameseLabels.js';

const MAX_TITLE_CHARS = 70;
const MAX_INTRODUCTION_CHARS = 1200;
const MAX_TAGS = 10;
const MAX_TAG_CHARS = 20;
const AI_GENERATED_TAG = 'AI生成作品';
const STORY_FOOTER_PATTERN = /\n?\s*(?:Created By AI Story Maker V[\d.]+|Generated By AI Story Maker V[\d.]+|Generated by Super FURU AI Story v[\d.]+)\s*$/i;
const TITLE_LABEL_PATTERN = /(?:^|\n)\s*(?:小説タイトル|タイトル|題名|作品名)\s*[:：]\s*([^\n]{1,100})/u;
const TITLE_LABEL_LINE_PATTERN = /^\s*(?:小説タイトル|タイトル|題名|作品名)\s*[:：]\s*([^\n]{1,100})\s*$/u;
const CHAPTER_HEADING_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?(?:(?:第[0-9０-９一二三四五六七八九十百千]+[章話節](?:[\t \u3000:：\-ー―・]+[^\n【】]{0,60})?)|(?:プロローグ|エピローグ|序章|終章)(?:[\t \u3000:：\-ー―・]+[^\n【】]{0,60})?)(?:[\t \u3000]*】)?[\t \u3000]*$/u;
const CHAPTER_HEADING_PREFIX_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?(?:(?:第[0-9０-９一二三四五六七八九十百千]+[章話節](?:[\t \u3000:：\-ー―・]+[^\n【】\s\u3000]{1,32})?)|(?:プロローグ|エピローグ|序章|終章)(?:[\t \u3000:：\-ー―・]+[^\n【】\s\u3000]{1,32})?)(?:[\t \u3000]*】)?[\t \u3000]+/u;
const STANDALONE_FINISH_PATTERN = /^[\t \u3000]*(?:【\s*)?完(?:\s*】)?[\t \u3000]*$/u;

export const ALPHAPOLIS_HOT_RANKING_OPTIONS = ['未選択', '男性向け', '女性向け'];
export const ALPHAPOLIS_CATEGORY_OPTIONS = [
  'カテゴリ選択',
  'ミステリー',
  'ホラー',
  'SF',
  'ファンタジー',
  '恋愛',
  'キャラ文芸',
  'ライト文芸',
  '青春',
  '現代文学',
  '大衆娯楽',
  '経済・企業',
  '歴史・時代',
  '児童書・童話',
  '絵本',
  'BL',
  'エッセイ・ノンフィクション',
];
export const ALPHAPOLIS_LENGTH_OPTIONS = ['ショートショート', '短編', '長編'];
export const ALPHAPOLIS_STATUS_OPTIONS = ['連載中', '完結'];
export const ALPHAPOLIS_RATING_OPTIONS = ['なし', 'R15', 'R18'];
export const ALPHAPOLIS_CHAPTER_SETTING_OPTIONS = ['設定しない', '新しい章を追加する'];

function normalizeText(value) {
  return String(value || '').replace(/\r\n?/g, '\n').trim();
}

function compactSpaces(value) {
  return String(value || '').replace(/\s+/g, ' ').trim();
}

function charLength(value) {
  return Array.from(String(value || '')).length;
}

function limitChars(value, max, suffix = '') {
  const chars = Array.from(String(value || '').trim());
  if (chars.length <= max) return chars.join('');
  const suffixChars = Array.from(suffix);
  const keep = Math.max(0, max - suffixChars.length);
  return `${chars.slice(0, keep).join('')}${suffix}`;
}

function stripStoryMakerFooter(text) {
  let current = normalizeText(text);
  for (let index = 0; index < 3; index += 1) {
    current = current.replace(STORY_FOOTER_PATTERN, '').trim();
  }
  return current;
}

function cleanTitleCandidate(value) {
  return compactSpaces(value)
    .replace(/^#+/, '')
    .replace(/^[「『【《〈"']+|[」』】》〉"']+$/g, '')
    .replace(/[。！？!?]+$/g, '')
    .trim();
}

function cleanHeadingLabel(value) {
  return compactSpaces(value)
    .replace(/^[#\s\u3000【]+|[】\s\u3000]+$/gu, '')
    .trim();
}

function isChapterHeadingLine(value) {
  return CHAPTER_HEADING_PATTERN.test(String(value || '').trim());
}

function isLikelyTitleLine(value) {
  const title = cleanTitleCandidate(value);
  return (
    title
    && charLength(title) <= MAX_TITLE_CHARS
    && !/[。！？!?]$/.test(value)
    && !isChapterHeadingLine(title)
    && !STANDALONE_FINISH_PATTERN.test(title)
    && !/^Created By|^Generated By/i.test(title)
  );
}

function extractTitle(text, settings = {}) {
  const body = stripStoryMakerFooter(text);
  const labeled = body.match(TITLE_LABEL_PATTERN);
  if (labeled) return limitChars(cleanTitleCandidate(labeled[1]), MAX_TITLE_CHARS);

  const lines = body.split('\n').map(line => line.trim()).filter(Boolean);
  const bracketed = lines[0]?.match(/^【(.{1,70})】$/u);
  if (bracketed && !isChapterHeadingLine(bracketed[1])) {
    return limitChars(cleanTitleCandidate(bracketed[1]), MAX_TITLE_CHARS);
  }
  const markdown = lines[0]?.match(/^[#＃]+\s*(.{1,70})$/u);
  if (markdown && !isChapterHeadingLine(markdown[1])) {
    return limitChars(cleanTitleCandidate(markdown[1]), MAX_TITLE_CHARS);
  }
  if (lines[0] && isLikelyTitleLine(lines[0])) {
    return limitChars(cleanTitleCandidate(lines[0]), MAX_TITLE_CHARS);
  }

  const theme = cleanTitleCandidate(settings.theme);
  const genre = cleanTitleCandidate(settings.genre);
  if (theme) return limitChars(`${theme}の物語`, MAX_TITLE_CHARS);
  if (genre) return limitChars(`${genre}の物語`, MAX_TITLE_CHARS);
  return '名称未設定の小説';
}

function dropTitleLine(body, title) {
  const lines = normalizeText(body).split('\n');
  const normalizedTitle = cleanTitleCandidate(title);
  if (!normalizedTitle || !lines.length) return body;
  return lines
    .filter((line, index) => {
      const trimmed = line.trim();
      const labeled = trimmed.match(TITLE_LABEL_LINE_PATTERN);
      if (labeled) {
        return cleanTitleCandidate(labeled[1]) !== normalizedTitle;
      }
      return !(index === 0 && cleanTitleCandidate(trimmed) === normalizedTitle);
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function stripChapterHeadingPrefix(value) {
  const line = compactSpaces(value);
  if (!line || isChapterHeadingLine(line)) return '';
  return line.replace(CHAPTER_HEADING_PREFIX_PATTERN, '').trim();
}

function cleanSubmissionBody(body) {
  return normalizeText(body)
    .split('\n')
    .filter(line => !TITLE_LABEL_LINE_PATTERN.test(line.trim()))
    .filter(line => !STANDALONE_FINISH_PATTERN.test(line.trim()))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function extractSubmissionBody(storyText, title) {
  const withoutFooter = stripStoryMakerFooter(storyText);
  return cleanSubmissionBody(dropTitleLine(withoutFooter, title));
}

function contentLines(text) {
  return normalizeText(text)
    .split('\n')
    .map(line => stripChapterHeadingPrefix(line))
    .filter(line => charLength(line) >= 8)
    .filter(line => !TITLE_LABEL_LINE_PATTERN.test(line));
}

function splitSentences(text) {
  const compact = compactSpaces(text);
  const matches = compact.match(/[^。！？!?]+[。！？!?]?/g) || [];
  return matches
    .map(sentence => sentence.trim())
    .filter(sentence => charLength(sentence) >= 8);
}

function buildIntroduction(body, title, settings = {}) {
  const summaryText = contentLines(body).join('\n');
  const sentences = splitSentences(summaryText);
  const lead = sentences.slice(0, 3).join('');
  if (lead) return limitChars(lead, MAX_INTRODUCTION_CHARS, '...');

  const theme = compactSpaces(settings.theme || '');
  const genre = compactSpaces(settings.genre || settings.modeLabel || '物語');
  const worldview = compactSpaces(settings.worldview || '');
  const axes = [worldview, theme].filter(Boolean).join('、');
  const frame = axes ? `${axes}を軸にした${genre}です。` : `${genre}として読める一作です。`;
  return limitChars(`『${title}』は、${frame}登場人物の選択と関係の変化を本文の温度感に沿って描きます。`, MAX_INTRODUCTION_CHARS, '...');
}

function normalizeTag(value) {
  return limitChars(
    compactSpaces(value)
      .replace(/^#+/, '')
      .replace(/[、。！？!?：:;；（）()\[\]{}「」『』【】]/g, '')
      .trim(),
    MAX_TAG_CHARS,
  );
}

function addTag(tags, value) {
  const tag = normalizeTag(value);
  if (tag && !tags.includes(tag)) tags.push(tag);
}

function findExactOption(values, options, { allowPlaceholder = true } = {}) {
  for (const value of values) {
    const text = compactSpaces(value);
    if (!text) continue;
    const match = options.find(option => option === text);
    if (match && (allowPlaceholder || match !== 'カテゴリ選択')) return match;
  }
  return '';
}

function inferHotRanking(settings = {}) {
  const direct = findExactOption([settings.hotGenre, settings.target, settings.modeLabel], ALPHAPOLIS_HOT_RANKING_OPTIONS);
  if (direct) return direct;
  const source = [
    settings.target,
    settings.modeLabel,
  ].filter(Boolean).join(' ').toLowerCase();
  if (/女性|女子|少女|乙女|bl|恋愛|ロマンス|レディース/.test(source)) return '女性向け';
  if (/男性|男子|少年|青年|メンズ/.test(source)) return '男性向け';
  return '未選択';
}

function inferCategory(settings = {}) {
  const direct = findExactOption([settings.category, settings.genre], ALPHAPOLIS_CATEGORY_OPTIONS, { allowPlaceholder: false });
  if (direct) return direct;
  const source = [
    settings.genre,
    settings.theme,
    settings.worldview,
    settings.modeLabel,
    settings.target,
  ].filter(Boolean).join(' ').toLowerCase();
  if (/ミステリ|推理|事件|探偵|サスペンス/.test(source)) return 'ミステリー';
  if (/ホラー|怪談|幽霊|呪|恐怖/.test(source)) return 'ホラー';
  if (/sf|宇宙|未来|ai|ロボ|サイバ|タイム/.test(source)) return 'SF';
  if (/ファンタジ|fantasy|異世界|魔法|剣|竜|ドラゴン/.test(source)) return 'ファンタジー';
  if (/恋愛|ラブコメ|romance|ロマンス/.test(source)) return '恋愛';
  if (/キャラ文芸|キャラクター文芸/.test(source)) return 'キャラ文芸';
  if (/ライト文芸/.test(source)) return 'ライト文芸';
  if (/青春|部活|学生|学園/.test(source)) return '青春';
  if (/現代文学|文学/.test(source)) return '現代文学';
  if (/大衆娯楽|娯楽|エンタメ|アクション|冒険/.test(source)) return '大衆娯楽';
  if (/経済|企業|会社|ビジネス|仕事|職場/.test(source)) return '経済・企業';
  if (/歴史|時代|戦国|江戸|明治|大正|幕末/.test(source)) return '歴史・時代';
  if (/児童|童話/.test(source)) return '児童書・童話';
  if (/絵本/.test(source)) return '絵本';
  if (/\bbl\b|ボーイズラブ|やおい/.test(source)) return 'BL';
  if (/エッセイ|随筆|ノンフィクション|実話/.test(source)) return 'エッセイ・ノンフィクション';
  return '大衆娯楽';
}

function inferLengthKind(body, episodes) {
  const chars = charLength(body);
  if ((episodes?.length || 0) >= 3 || chars >= 10000) return '長編';
  if ((episodes?.length || 0) <= 1 && chars <= 2200) return 'ショートショート';
  return '短編';
}

function inferWritingStatus(body, episodes) {
  if (/【完】|完結|おわり|終わり/.test(body)) return '完結';
  if ((episodes?.length || 0) <= 1 && charLength(body) < 8000) return '完結';
  return '連載中';
}

function detectRating(body) {
  if (/R18|成人向け|官能|性行為|性交|露骨な性描写/.test(body)) return 'R18';
  if (/R15|血|惨殺|拷問|遺体|死体|虐殺|切断|内臓|グロ|残酷|暴力|殺人|戦闘|性的/.test(body)) return 'R15';
  return 'なし';
}

function buildTags(settings = {}, category) {
  const tags = [];
  addTag(tags, AI_GENERATED_TAG);
  if (category !== 'カテゴリ選択') addTag(tags, category);
  addTag(tags, settings.theme);
  addTag(tags, settings.genre);
  addTag(tags, settings.worldview);
  addTag(tags, settings.target);
  addTag(tags, settings.ending);
  addTag(tags, settings.narration);
  return tags.slice(0, MAX_TAGS);
}

function buildCategoryWarning(category, body, settings = {}) {
  const source = [
    body,
    settings.genre,
    settings.theme,
    settings.worldview,
    settings.modeLabel,
  ].filter(Boolean).join(' ');
  const fantasyErrorTargets = ['ミステリー', 'ホラー', 'キャラ文芸', 'ライト文芸', '青春', '現代文学', '大衆娯楽', '経済・企業', '絵本'];
  if (
    fantasyErrorTargets.includes(category)
    && /異世界|ゲーム世界|転生|転移|悪役令嬢|婚約破棄|ファンタジー/.test(source)
  ) {
    return `${category}は、異世界/転生/転移/悪役令嬢/婚約破棄/異世界ファンタジー要素があるとカテゴリーエラー扱いになる可能性があります。`;
  }
  if (category === '児童書・童話' && /悪役令嬢|婚約破棄/.test(source)) {
    return '児童書・童話は、悪役令嬢/婚約破棄などがあるとカテゴリーエラー扱いになる可能性があります。';
  }
  if (category === '歴史・時代' && /タイムスリップ|転生|転移|異世界|ファンタジー/.test(source)) {
    return '歴史・時代は、タイムスリップ/転生/転移/異世界ファンタジー要素があるとカテゴリーエラー扱いになる可能性があります。';
  }
  return '';
}

function buildGuidelineChecks({ body, category, rating, tags, settings }) {
  const checks = [
    '他投稿サービスとの重複投稿は可。重複投稿先の明記は任意。',
    tags.includes(AI_GENERATED_TAG)
      ? '生成AIを本文作成の主目的に使った作品向けに「AI生成作品」タグを付与済み。'
      : '生成AIを本文作成の主目的に使った場合は「AI生成作品」タグを推奨。',
    '二次創作、第三者の権利を侵害する表紙画像、商品化済み/商品化予定作品の内部投稿は禁止。',
    '大量投稿、小説・漫画としての体を成していない投稿、公序良俗に反する内容は禁止。',
  ];
  const categoryWarning = buildCategoryWarning(category, body, settings);
  if (categoryWarning) checks.push(categoryWarning);
  checks.push(
    rating === 'なし'
      ? 'R指定は「なし」候補。性的/暴力/残虐表現がある場合はR15/R18を再確認。'
      : `R指定は「${rating}」候補。最終的な対象年齢設定は本文全体の表現量と強さで再確認。`,
  );
  return checks;
}

function buildDefaultEpisode(body, title) {
  return [{
    chapterSetting: '設定しない',
    chapterName: '',
    sectionName: '設定しない',
    episodeTitle: limitChars(title || '第1話', MAX_TITLE_CHARS),
    body: normalizeText(body),
  }];
}

function splitAlphapolisEpisodes(body, title) {
  const lines = normalizeText(body).split('\n');
  const episodes = [];
  const preface = [];
  let current = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (isChapterHeadingLine(trimmed)) {
      if (current) episodes.push(current);
      const label = cleanHeadingLabel(trimmed) || `第${episodes.length + 1}章`;
      current = {
        chapterSetting: '新しい章を追加する',
        chapterName: limitChars(label, MAX_TITLE_CHARS),
        sectionName: limitChars(label, MAX_TITLE_CHARS),
        episodeTitle: limitChars(label, MAX_TITLE_CHARS),
        lines: [],
      };
      preface.length = 0;
    } else if (current) {
      current.lines.push(line);
    } else if (trimmed) {
      preface.push(line);
    }
  }
  if (current) episodes.push(current);

  const mapped = episodes
    .map(episode => ({
      chapterSetting: episode.chapterSetting,
      chapterName: episode.chapterName,
      sectionName: episode.sectionName,
      episodeTitle: episode.episodeTitle,
      body: normalizeText(episode.lines.join('\n')),
    }))
    .filter(episode => charLength(episode.body) >= 40);

  if (preface.length && charLength(preface.join('\n')) >= 40) {
    mapped.unshift({
      chapterSetting: '設定しない',
      chapterName: '',
      sectionName: '設定しない',
      episodeTitle: limitChars(title || '第1話', MAX_TITLE_CHARS),
      body: normalizeText(preface.join('\n')),
    });
  }

  return mapped.length ? mapped : buildDefaultEpisode(body, title);
}

export function buildAlphapolisPreview({ storyText = '', settings = {} } = {}) {
  const title = extractTitle(storyText, settings);
  const body = extractSubmissionBody(storyText, title);
  const episodes = splitAlphapolisEpisodes(body, title);
  const category = inferCategory(settings);
  const preview = {
    title,
    introduction: buildIntroduction(body, title, settings),
    hotGenre: inferHotRanking(settings),
    category,
    lengthKind: inferLengthKind(body, episodes),
    writingStatus: inferWritingStatus(body, episodes),
    rating: detectRating(body),
    tags: buildTags(settings, category),
    coverImage: '未設定',
    impressions: '有り',
    guideline: '投稿前に公式投稿ガイドラインを確認',
    body,
    episodes,
    options: {
      hotRanking: ALPHAPOLIS_HOT_RANKING_OPTIONS,
      category: ALPHAPOLIS_CATEGORY_OPTIONS,
      length: ALPHAPOLIS_LENGTH_OPTIONS,
      status: ALPHAPOLIS_STATUS_OPTIONS,
      rating: ALPHAPOLIS_RATING_OPTIONS,
      chapterSetting: ALPHAPOLIS_CHAPTER_SETTING_OPTIONS,
    },
  };
  preview.guidelineChecks = buildGuidelineChecks({
    body,
    category,
    rating: preview.rating,
    tags: preview.tags,
    settings,
  });
  preview.copyAll = formatAlphapolisPreview(preview);
  return preview;
}

export function formatAlphapolisPreview(preview) {
  const lines = [
    'アルファポリス作品情報',
    `タイトル: ${preview.title}`,
    `内容紹介:\n${preview.introduction}`,
    `HOTランキング用ジャンル: ${preview.hotGenre}`,
    `カテゴリ: ${preview.category}`,
    `長編・短編: ${preview.lengthKind}`,
    `執筆状態: ${preview.writingStatus}`,
    `R指定: ${preview.rating}`,
    `タグ:\n${preview.tags.map((tag, index) => `${index + 1}. ${tag}`).join('\n')}`,
    `表紙画像: ${preview.coverImage}`,
    `感想の受付: ${preview.impressions}`,
    `投稿ガイドライン: ${preview.guideline}`,
    `投稿前チェック:\n${preview.guidelineChecks.map((item, index) => `${index + 1}. ${item}`).join('\n')}`,
    '話の貼り付け',
  ];
  preview.episodes.forEach((episode, index) => {
    const episodeLines = [
      `# ${index + 1}`,
      `章の設定: ${episode.chapterSetting}`,
    ];
    if (episode.chapterSetting === '新しい章を追加する') {
      episodeLines.push(`新しい章名: ${episode.chapterName}`);
    }
    episodeLines.push(
      `話のタイトル: ${episode.episodeTitle}`,
      `本文:\n${episode.body}`,
    );
    lines.push(episodeLines.join('\n'));
  });
  return lines.join('\n\n');
}

function readActiveChipText(selector) {
  return document.querySelector(selector)?.textContent?.trim() || '';
}

function readInputValue(id) {
  return document.getElementById(id)?.value?.trim() || '';
}

function readAxisValue(axis) {
  return (
    readInputValue(`${axis}-custom`)
    || readActiveChipText(`#${axis}-sub-chips .chip.active`)
    || readActiveChipText(`#${axis}-cat-chips .chip.active`)
  );
}

function readSettingsFromDom() {
  return {
    modeLabel: readInputValue('mode-custom') || readActiveChipText('#mode-chips .chip.active'),
    theme: readAxisValue('theme'),
    genre: readAxisValue('genre'),
    worldview: readAxisValue('worldview'),
    target: readAxisValue('target'),
    era: readAxisValue('era'),
    ending: readAxisValue('ending'),
    narration: readAxisValue('narr'),
  };
}

function renderCopyButton(kind, options = {}) {
  const label = options.label || 'Sao chép';
  const title = options.title || `Sao chép ${label}`;
  const index = options.index === undefined ? '' : ` data-copy-index="${Ce(String(options.index))}"`;
  const className = options.className ? ` ${options.className}` : '';
  return `<button type="button" class="btn-secondary kakuyomu-copy-btn alphapolis-copy-btn${className}" data-copy-kind="${Ce(kind)}"${index} title="${Ce(title)}" aria-label="${Ce(title)}">${Ce(label)}</button>`;
}

function renderRow({ label, value, kind, note = '', multiline = false, contentHtml = '', hideAction = false }) {
  const valueClass = multiline ? 'kakuyomu-preview-value is-multiline' : 'kakuyomu-preview-value';
  const body = contentHtml || `<div class="${valueClass}">${Ce(getVietnameseLabel(value))}</div>`;
  const noteHtml = note ? `<div class="kakuyomu-preview-note">${Ce(note)}</div>` : '';
  const actionHtml = hideAction ? '' : renderCopyButton(kind);
  return `
    <div class="kakuyomu-preview-row alphapolis-preview-row">
      <div class="kakuyomu-preview-label">${Ce(label)}</div>
      <div class="kakuyomu-preview-content">${body}${noteHtml}</div>
      <div class="kakuyomu-preview-actions">${actionHtml}</div>
    </div>
  `;
}

function renderOptionNote(options) {
  return `Lựa chọn: ${options.map(getVietnameseLabel).join(' / ')}`;
}

function renderTags(preview) {
  const tags = preview.tags.map((tag, index) => `
    <span class="kakuyomu-tag-item">
      <span class="kakuyomu-tag">${Ce(tag)}</span>
      ${renderCopyButton('tag', { label: 'Sao chép thẻ', index })}
    </span>
  `).join('');
  return renderRow({
    label: 'Thẻ',
    kind: 'tags',
    note: 'Mỗi thẻ tối đa 20 ký tự, nhiều nhất 10 thẻ. Mặc định gồm thẻ tác phẩm do AI tạo.',
    hideAction: true,
    contentHtml: `<div class="kakuyomu-tag-list">${tags}</div>`,
  });
}

function renderEpisode(episode, index) {
  const chapterNameMeta = episode.chapterSetting === '新しい章を追加する'
    ? ` / Tên chương mới: ${Ce(episode.chapterName)}`
    : '';
  return `
    <section class="kakuyomu-body-block alphapolis-episode-block">
      <div class="kakuyomu-body-block-head">
        <div>
          <div class="kakuyomu-body-block-title">#${index + 1} ${Ce(episode.episodeTitle)}</div>
          <div class="kakuyomu-body-block-meta">${charLength(episode.body)} ký tự / Thiết lập chương: ${Ce(getVietnameseLabel(episode.chapterSetting))}${chapterNameMeta}</div>
        </div>
        <div class="kakuyomu-body-block-actions">
          ${renderCopyButton('episodeTitle', { label: 'Sao chép tiêu đề tập', index })}
          ${renderCopyButton('episodeBody', { label: 'Sao chép nội dung', index, className: 'kakuyomu-chapter-copy' })}
        </div>
      </div>
      <pre class="kakuyomu-body-preview kakuyomu-chapter-preview">${Ce(episode.body)}</pre>
    </section>
  `;
}

function renderEpisodes(preview) {
  return `<div class="kakuyomu-body-sections alphapolis-episode-list">${preview.episodes.map((episode, index) => renderEpisode(episode, index)).join('')}</div>`;
}

export function renderAlphapolisPreview(preview) {
  return `
    <div class="kakuyomu-preview-titlebar alphapolis-preview-titlebar">
      <div>
        <div class="kakuyomu-preview-kicker">Xem trước biểu mẫu Alphapolis</div>
        <div class="kakuyomu-preview-name">${Ce(preview.title)}</div>
      </div>
      <span class="kakuyomu-preview-count">${charLength(preview.title)} / ${MAX_TITLE_CHARS} ký tự</span>
    </div>
    ${renderRow({ label: 'Tiêu đề', value: preview.title, kind: 'title', note: 'Tối đa 70 ký tự' })}
    ${renderRow({ label: 'Giới thiệu nội dung', value: preview.introduction, kind: 'introduction', multiline: true, note: 'Tối đa 1.200 ký tự' })}
    ${renderRow({ label: 'Thể loại xếp hạng HOT', value: preview.hotGenre, kind: 'hotGenre', note: renderOptionNote(preview.options.hotRanking) })}
    ${renderRow({ label: 'Danh mục', value: preview.category, kind: 'category', note: renderOptionNote(preview.options.category) })}
    ${renderRow({ label: 'Độ dài', value: preview.lengthKind, kind: 'lengthKind', note: renderOptionNote(preview.options.length) })}
    ${renderRow({ label: 'Trạng thái viết', value: preview.writingStatus, kind: 'writingStatus', note: renderOptionNote(preview.options.status) })}
    ${renderRow({ label: 'Phân loại độ tuổi', value: preview.rating, kind: 'rating', note: renderOptionNote(preview.options.rating) })}
    ${renderTags(preview)}
    ${renderRow({ label: 'Ảnh bìa', value: preview.coverImage, kind: 'coverImage' })}
    ${renderRow({ label: 'Nhận bình luận', value: preview.impressions, kind: 'impressions' })}
    ${renderRow({ label: 'Hướng dẫn đăng bài', value: preview.guideline, kind: 'guideline' })}
    ${renderRow({ label: 'Kiểm tra trước khi đăng', value: preview.guidelineChecks.join('\n'), kind: 'guidelineChecks', multiline: true, hideAction: true })}
    ${renderRow({ label: 'Đăng tập', kind: 'episodeBody', multiline: true, hideAction: true, contentHtml: renderEpisodes(preview) })}
  `;
}

export function getAlphapolisCopyValue(preview, kind, options = {}) {
  const index = Number(options.episodeIndex ?? options.tagIndex);
  if (kind === 'tag') return Number.isInteger(index) ? preview.tags?.[index] || '' : '';
  if (kind === 'chapterSetting') return Number.isInteger(index) ? preview.episodes?.[index]?.chapterSetting || '' : '';
  if (kind === 'chapterName') return Number.isInteger(index) ? preview.episodes?.[index]?.chapterName || '' : '';
  if (kind === 'sectionName') return Number.isInteger(index) ? preview.episodes?.[index]?.sectionName || '' : '';
  if (kind === 'episodeTitle') return Number.isInteger(index) ? preview.episodes?.[index]?.episodeTitle || '' : '';
  if (kind === 'episodeBody') return Number.isInteger(index) ? preview.episodes?.[index]?.body || '' : '';
  const values = {
    all: preview.copyAll,
    title: preview.title,
    introduction: preview.introduction,
    hotGenre: preview.hotGenre,
    category: preview.category,
    lengthKind: preview.lengthKind,
    writingStatus: preview.writingStatus,
    rating: preview.rating,
    tags: preview.tags.join('\n'),
    coverImage: preview.coverImage,
    impressions: preview.impressions,
    guideline: preview.guideline,
    guidelineChecks: preview.guidelineChecks.join('\n'),
    body: preview.body,
  };
  return values[kind] || '';
}

function restoreButtonText(button, originalText) {
  setTimeout(() => {
    button.textContent = originalText;
    button.classList.remove('is-copied');
  }, 1200);
}

async function copyText(value, button) {
  const text = String(value || '');
  if (!text) return;
  const originalText = button.textContent;
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.setAttribute('readonly', '');
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    textarea.remove();
  }
  button.textContent = 'Đã sao chép';
  button.classList.add('is-copied');
  restoreButtonText(button, originalText);
}

function saveTextFile(value, button) {
  const text = String(value || '');
  if (!text) return;
  const originalText = button.textContent;
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = buildStoryExportFileName('AlphapolisForm', 'txt');
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  button.textContent = 'Đã lưu';
  button.classList.add('is-copied');
  restoreButtonText(button, originalText);
}

function outputHasStory(outputEl) {
  if (!outputEl || outputEl.classList.contains('empty')) return false;
  return charLength(stripStoryMakerFooter(outputEl.innerText || outputEl.textContent || '')) >= 40;
}

function isStoryGenerationActive() {
  const settingsEl = document.getElementById('settings');
  const generateButton = document.getElementById('btn-generate');
  return Boolean(settingsEl?.classList.contains('generating') || generateButton?.disabled);
}

export function installAlphapolisAssist() {
  const outputEl = document.getElementById('output');
  const rootEl = document.getElementById('alphapolis-assist');
  const checkbox = document.getElementById('alphapolis-assist-enable');
  const bodyEl = document.getElementById('alphapolis-assist-body');
  const previewEl = document.getElementById('alphapolis-form-preview');
  const statusEl = document.getElementById('alphapolis-assist-status');
  if (!outputEl || !rootEl || !checkbox || !bodyEl || !previewEl || !statusEl) return;

  let lastPreview = null;
  let queued = false;
  let busy = false;

  const setCopyControlsDisabled = disabled => {
    bodyEl.querySelectorAll('.alphapolis-copy-btn, .alphapolis-save-btn').forEach(button => {
      button.disabled = Boolean(disabled);
    });
  };

  const applyLockedUi = (value, message = 'Cập nhật nội dung mới nhất sau khi xử lý xong') => {
    const locked = Boolean(value);
    rootEl.classList.toggle('is-busy', locked);
    rootEl.setAttribute('aria-busy', locked ? 'true' : 'false');
    checkbox.disabled = locked || !outputHasStory(outputEl);
    setCopyControlsDisabled(locked);
    if (locked) statusEl.textContent = message;
  };

  const setBusy = value => {
    busy = Boolean(value);
    applyLockedUi(busy);
  };

  const refresh = () => {
    queued = false;
    const generationActive = isStoryGenerationActive();
    if (busy || generationActive) {
      applyLockedUi(true, generationActive ? 'Cập nhật nội dung mới nhất sau khi tạo xong' : 'Cập nhật nội dung mới nhất sau khi xử lý xong');
      return;
    }
    applyLockedUi(false);
    const enabled = checkbox.checked;
    const canPreview = outputHasStory(outputEl);
    checkbox.disabled = !canPreview;
    bodyEl.classList.toggle('hidden', !enabled || !canPreview);
    if (!canPreview) {
      lastPreview = null;
      statusEl.textContent = 'Hiển thị sau khi có kết quả';
      previewEl.innerHTML = '';
      setCopyControlsDisabled(true);
      return;
    }
    const storyText = outputEl.innerText || outputEl.textContent || '';
    lastPreview = buildAlphapolisPreview({
      storyText,
      settings: readSettingsFromDom(),
    });
    statusEl.textContent = enabled
      ? `Đang hiển thị: ${lastPreview.episodes.length} tập / ${lastPreview.tags.length} thẻ đề xuất`
      : 'Đánh dấu để hiển thị';
    if (enabled) previewEl.innerHTML = renderAlphapolisPreview(lastPreview);
    setCopyControlsDisabled(!enabled);
  };

  const scheduleRefresh = () => {
    if (queued) return;
    queued = true;
    window.requestAnimationFrame(refresh);
  };

  checkbox.checked = false;
  checkbox.addEventListener('change', refresh);
  window.addEventListener('story-maker:alphapolis-busy', event => {
    setBusy(event.detail?.busy);
    if (!busy) scheduleRefresh();
  });
  window.addEventListener('story-maker:alphapolis-refresh', scheduleRefresh);

  bodyEl.addEventListener('click', event => {
    const saveButton = event.target?.closest?.('.alphapolis-save-btn');
    if (saveButton && !saveButton.disabled && !busy && lastPreview) {
      saveTextFile(lastPreview.copyAll, saveButton);
      return;
    }
    const button = event.target?.closest?.('.alphapolis-copy-btn');
    if (!button || button.disabled || busy || !lastPreview) return;
    copyText(getAlphapolisCopyValue(lastPreview, button.dataset.copyKind, {
      episodeIndex: button.dataset.copyIndex,
      tagIndex: button.dataset.copyIndex,
    }), button);
  });

  ['mode', 'theme', 'genre', 'worldview', 'target', 'era', 'ending', 'narr'].forEach(axis => {
    document.getElementById(`${axis}-custom`)?.addEventListener('input', scheduleRefresh);
    document.getElementById(`${axis}-custom`)?.addEventListener('change', scheduleRefresh);
  });
  document.addEventListener('click', event => {
    if (event.target?.closest?.('.chip, .btn-all-random, #btn-rand-mode')) {
      setTimeout(scheduleRefresh, 0);
    }
  });

  const observer = new MutationObserver(scheduleRefresh);
  observer.observe(outputEl, {
    childList: true,
    characterData: true,
    subtree: true,
    attributes: true,
    attributeFilter: ['class'],
  });
  const settingsEl = document.getElementById('settings');
  const generateButton = document.getElementById('btn-generate');
  if (settingsEl) {
    observer.observe(settingsEl, {
      attributes: true,
      attributeFilter: ['class'],
    });
  }
  if (generateButton) {
    observer.observe(generateButton, {
      childList: true,
      characterData: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['disabled', 'class'],
    });
  }
  refresh();
}
