import { Ce } from './domHelpers.js';
import { buildStoryExportFileName } from './fileIoHelpers.js';
import { getVietnameseLabel } from './vietnameseLabels.js';

const AI_USE_TAG = 'AI本文利用';
const MAX_CATCH_COPY_CHARS = 35;
const MAX_TAGS = 8;
const MAX_TAG_CHARS = 20;
const STORY_FOOTER_PATTERN = /\n?\s*(?:Created By AI Story Maker V[\d.]+|Generated By AI Story Maker V[\d.]+|Generated by Super FURU AI Story v[\d.]+)\s*$/i;
const CHAPTER_HEADING_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?第[\d０-９一二三四五六七八九十]+[章節話](?:[\t \u3000:：\-ー―／/・]+[^\n。！？!?]{0,48})?(?:[\t \u3000]*】)?[\t \u3000]*$/u;
const CHAPTER_HEADING_PREFIX_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?第[\d０-９一二三四五六七八九十]+[章節話](?:[\t \u3000:：\-ー―／/・]+[^\n。！？!?\s\u3000]{1,32})?[\t \u3000]+/u;
const TITLE_LABEL_LINE_PATTERN = /^[\t \u3000]*(?:小説タイトル|タイトル|題名|作品名)\s*[:：]\s*([^\n]{1,100})[\t \u3000]*$/u;
const TOP_LEVEL_CHAPTER_HEADING_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?第[\d０-９一二三四五六七八九十]+章(?:[\t \u3000:：\-ー―／/・]+[^\n。！？!?]{0,48})?(?:[\t \u3000]*】)?[\t \u3000]*$/u;
const SUBSECTION_HEADING_PATTERN = /^[\t \u3000]*(?:#{1,6}[\t \u3000]*)?(?:【[\t \u3000]*)?第[\d０-９一二三四五六七八九十]+節(?:[\t \u3000:：\-ー―／/・]+[^\n。！？!?]{0,48})?(?:[\t \u3000]*】)?[\t \u3000]*$/u;
const STANDALONE_FINISH_PATTERN = /^[\t \u3000]*【?\s*完\s*】?[\t \u3000]*$/u;

const GENRE_RULES = [
  { genre: 'ラブコメ', pattern: /ラブコメ|恋愛喜劇|ロマンチックコメディ/ },
  { genre: '恋愛', pattern: /恋愛|ロマンス|片想い|片思い|両想い|初恋/ },
  { genre: '現代ファンタジー', pattern: /現代ファンタジ|都市伝説|怪異|妖怪|異能|能力/ },
  { genre: '異世界ファンタジー', pattern: /異世界|ファンタジ|魔法|勇者|魔王|剣|竜|ドラゴン|冒険/ },
  { genre: 'ホラー', pattern: /ホラー|恐怖|怪談|心霊|幽霊|呪い|ゾンビ/ },
  { genre: 'ミステリー', pattern: /ミステリ|推理|探偵|謎|事件|殺人|サスペンス/ },
  { genre: 'SF', pattern: /sf|ｓｆ|宇宙|未来|ロボ|サイバー|ai|人工知能|タイム|量子/ },
  { genre: '歴史・時代・伝奇', pattern: /歴史|時代|伝奇|幕末|江戸|戦国|明治|大正|平安/ },
  { genre: 'エッセイ・ノンフィクション', pattern: /エッセイ|随筆|ノンフィクション|実話|日記|体験談/ },
  { genre: '現代ドラマ', pattern: /現代|ドラマ|青春|家族|仕事|職場|日常|学校|学園/ },
  { genre: '詩・童話・その他', pattern: /詩|童話|寓話|絵本|掌編/ },
];

const IMAGE_COLORS = {
  ラブコメ: { label: 'ピンク系', hex: '#f472b6' },
  恋愛: { label: 'ローズ系', hex: '#fb7185' },
  現代ファンタジー: { label: '青紫系', hex: '#6366f1' },
  異世界ファンタジー: { label: '紫系', hex: '#8b6cff' },
  ホラー: { label: '黒系', hex: '#262626' },
  ミステリー: { label: '藍色系', hex: '#334155' },
  SF: { label: 'シアン系', hex: '#06b6d4' },
  '歴史・時代・伝奇': { label: '深緑系', hex: '#166534' },
  'エッセイ・ノンフィクション': { label: 'グレー系', hex: '#64748b' },
  現代ドラマ: { label: '青緑系', hex: '#0f766e' },
  '詩・童話・その他': { label: '橙系', hex: '#f59e0b' },
};

function normalizeText(value) {
  return String(value || '').replace(/\r\n?/g, '\n').trim();
}

function compactSpaces(value) {
  return String(value || '').replace(/\s+/g, ' ').trim();
}

function charLength(value) {
  return Array.from(String(value || '')).length;
}

export function limitJapaneseChars(value, max, suffix = '') {
  const chars = Array.from(String(value || '').trim());
  if (chars.length <= max) return chars.join('');
  const suffixChars = Array.from(suffix);
  const keep = Math.max(0, max - suffixChars.length);
  return `${chars.slice(0, keep).join('')}${suffix}`;
}

export function stripStoryMakerFooter(text) {
  let current = normalizeText(text);
  for (let i = 0; i < 3; i += 1) {
    current = current.replace(STORY_FOOTER_PATTERN, '').trim();
  }
  return current;
}

function cleanTitleCandidate(value) {
  return compactSpaces(value)
    .replace(/^[#＃\s]+/, '')
    .replace(/^["'「『【]+|["'」』】]+$/g, '')
    .replace(/[。！？!?]+$/g, '')
    .trim();
}

function isLikelyTitleLine(value) {
  const title = cleanTitleCandidate(value);
  return (
    title.length > 0
    && charLength(title) <= 42
    && !/[。！？!?]$/.test(value)
    && !/^(第[0-9０-９一二三四五六七八九十]+[章節話]|Created By|Generated By)/i.test(title)
  );
}

export function extractStoryTitle(text, settings = {}) {
  const body = stripStoryMakerFooter(text);
  const labeled = body.match(/(?:^|\n)\s*(?:タイトル|題名|作品名)\s*[:：]\s*([^\n]{1,80})/);
  if (labeled) return limitJapaneseChars(cleanTitleCandidate(labeled[1]), 42);

  const lines = body.split('\n').map(line => line.trim()).filter(Boolean);
  const bracketed = lines[0]?.match(/^【(.{1,60})】$/);
  if (bracketed) return limitJapaneseChars(cleanTitleCandidate(bracketed[1]), 42);
  const heading = lines[0]?.match(/^[#＃]+\s*(.{1,60})$/);
  if (heading) return limitJapaneseChars(cleanTitleCandidate(heading[1]), 42);
  if (lines[0] && isLikelyTitleLine(lines[0])) {
    return limitJapaneseChars(cleanTitleCandidate(lines[0]), 42);
  }

  const theme = cleanTitleCandidate(settings.theme);
  const genre = cleanTitleCandidate(settings.genre);
  if (theme) return limitJapaneseChars(`${theme}の物語`, 42);
  if (genre) return limitJapaneseChars(`${genre}の物語`, 42);
  return '名称未設定の小説';
}

function dropTitleLine(body, title) {
  const lines = normalizeText(body).split('\n');
  const normalizedTitle = cleanTitleCandidate(title);
  if (!normalizedTitle || !lines.length) return body;
  const first = cleanTitleCandidate(lines[0]);
  const shouldDropFirst = (
    first === normalizedTitle
    || cleanTitleCandidate(first.replace(/^(?:小説タイトル|タイトル|題名|作品名)\s*[:：]\s*/u, '')) === normalizedTitle
  );
  return lines
    .filter((line, index) => {
      if (index === 0 && shouldDropFirst) return false;
      const match = String(line || '').match(TITLE_LABEL_LINE_PATTERN);
      if (!match) return true;
      const candidate = cleanTitleCandidate(match[1]);
      return candidate && candidate !== normalizedTitle;
    })
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function splitSentences(text) {
  const compact = compactSpaces(text);
  const matches = compact.match(/[^。！？!?]+[。！？!?]?/g) || [];
  return matches
    .map(sentence => sentence.trim())
    .filter(sentence => charLength(sentence) >= 8);
}

function isChapterHeadingLine(value) {
  return CHAPTER_HEADING_PATTERN.test(String(value || '').trim());
}

function stripChapterHeadingPrefix(value) {
  const line = compactSpaces(value);
  if (!line || isChapterHeadingLine(line)) return '';
  return line.replace(CHAPTER_HEADING_PREFIX_PATTERN, '').trim();
}

function storyTextForFormSummary(body, title) {
  const withoutTitle = dropTitleLine(body, title);
  return normalizeText(withoutTitle)
    .split('\n')
    .map(line => stripChapterHeadingPrefix(line))
    .filter(Boolean)
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function cleanSubmissionBodyArtifacts(body) {
  const lines = normalizeText(body).split('\n');
  const hasTopLevelChapters = lines.some(line => TOP_LEVEL_CHAPTER_HEADING_PATTERN.test(line.trim()));
  return lines
    .filter(line => !TITLE_LABEL_LINE_PATTERN.test(line.trim()))
    .filter(line => !(hasTopLevelChapters && SUBSECTION_HEADING_PATTERN.test(line.trim())))
    .filter(line => !(hasTopLevelChapters && STANDALONE_FINISH_PATTERN.test(line.trim())))
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

function contentLines(text) {
  return normalizeText(text)
    .split('\n')
    .map(line => stripChapterHeadingPrefix(line))
    .filter(line => charLength(line) >= 8)
    .filter(line => !/^(?:タイトル|題名|作品名)\s*[:：]/.test(line))
    .filter(line => !/^Created By AI Story Maker/i.test(line));
}

function buildCatchCopy(body, title, settings = {}) {
  const summaryBody = storyTextForFormSummary(body, title);
  const lead = splitSentences(summaryBody)[0] || contentLines(summaryBody)[0] || '';
  if (lead) {
    return limitJapaneseChars(lead.replace(/[。！？!?]+$/g, ''), MAX_CATCH_COPY_CHARS, '…');
  }
  const theme = compactSpaces(settings.theme || title);
  const ending = compactSpaces(settings.ending || settings.genre || '物語');
  return limitJapaneseChars(`${theme}が揺らす、${ending}の一作`, MAX_CATCH_COPY_CHARS, '…');
}

function buildIntroduction(body, title, settings = {}) {
  const summaryBody = storyTextForFormSummary(body, title);
  const sentences = splitSentences(summaryBody);
  const lines = contentLines(summaryBody);
  const lead = sentences[0] || lines[0] || '';
  const theme = compactSpaces(settings.theme || '');
  const genre = compactSpaces(settings.genre || settings.modeLabel || '物語');
  const worldview = compactSpaces(settings.worldview || '');
  const ending = compactSpaces(settings.ending || '');
  const titleLead = title && title !== '名称未設定の小説' ? `『${title}』は、` : '';
  const axes = [
    worldview ? `${worldview}を舞台に` : '',
    theme ? `${theme}を軸に` : '',
  ].filter(Boolean).join('、');
  const frame = `${titleLead}${axes ? `${axes}、` : ''}${genre}として読める一作です。`;
  const leadLine = lead
    ? `物語は「${limitJapaneseChars(lead.replace(/[。！？!?]+$/g, ''), 120, '…')}」から動き出します。`
    : '';
  const endingLine = ending ? `${ending}へ向かって、` : '';
  return limitJapaneseChars(
    `${frame}${leadLine}${endingLine}登場人物の迷い、選択、関係の変化を本文の温度感そのままに描きます。`,
    700,
    '…',
  );
}

export function suggestKakuyomuGenre(settings = {}) {
  const source = [
    settings.genre,
    settings.theme,
    settings.worldview,
    settings.modeLabel,
    settings.target,
  ].filter(Boolean).join(' ').toLowerCase();
  const rule = GENRE_RULES.find(item => item.pattern.test(source));
  return rule?.genre || '詩・童話・その他';
}

export function detectSelfRatings(text) {
  const body = stripStoryMakerFooter(text);
  const ratings = [];
  if (/血|惨殺|拷問|遺体|死体|虐殺|切断|内臓|グロ|残酷/.test(body)) {
    ratings.push('残酷描写有り');
  }
  if (/暴力|殴|蹴|銃|刀|刺|戦闘|殺す|殺し|爆発|戦争|武器/.test(body)) {
    ratings.push('暴力描写有り');
  }
  if (/性描写|性交|官能|性的|裸|裸体|濡れ場|成人向け/.test(body)) {
    ratings.push('性描写有り');
  }
  return [...new Set(ratings)];
}

function normalizeTag(value) {
  return limitJapaneseChars(
    compactSpaces(value)
      .replace(/^#+/, '')
      .replace(/[、。！？!?：:;；（）()\[\]{}「」『』【】]/g, '')
      .trim(),
    MAX_TAG_CHARS,
  );
}

function addTag(tags, value) {
  const tag = normalizeTag(value);
  if (!tag) return;
  if (!tags.includes(tag)) tags.push(tag);
}

export function createKakuyomuTags({ settings = {}, kakuyomuGenre = '' } = {}) {
  const tags = [];
  addTag(tags, AI_USE_TAG);
  addTag(tags, kakuyomuGenre);
  addTag(tags, String(settings.modeLabel || '').replace(/モード|風/g, ''));
  addTag(tags, settings.theme);
  addTag(tags, settings.genre);
  addTag(tags, settings.worldview);
  addTag(tags, settings.ending);
  addTag(tags, settings.target);
  addTag(tags, settings.narration);
  return tags.slice(0, MAX_TAGS);
}

function chooseImageColor(kakuyomuGenre) {
  return IMAGE_COLORS[kakuyomuGenre] || IMAGE_COLORS['詩・童話・その他'];
}

function inferWorkStatus(settings = {}) {
  const mode = String(settings.modeLabel || '');
  if (/長編|連載/.test(mode)) return '連載中';
  return '完結済（この本文だけで投稿する場合）';
}

export function formatKakuyomuPreview(preview) {
  const selfRating = preview.selfRatings.length ? preview.selfRatings.join(' / ') : '該当なし推奨';
  return [
    `小説タイトル: ${preview.title}`,
    `連載状態: ${preview.workStatus}`,
    `種類: ${preview.workType}`,
    `ジャンル: ${preview.genre}`,
    `キャッチコピー: ${preview.catchCopy}`,
    `紹介文:\n${preview.introduction}`,
    `セルフレイティング: ${selfRating}`,
    `タグ: ${preview.tags.join(' / ')}`,
    `コンテスト: ${preview.contest}`,
    `自主企画: ${preview.userEvent}`,
    `コレクション: ${preview.collection}`,
    `イメージカラー: ${preview.imageColor.label} (${preview.imageColor.hex})`,
    `広告表示: ${preview.adDisplay}`,
    `予約投稿の公開日時: ${preview.reservedPublish}`,
    `更新スケジュール: ${preview.updateSchedule}`,
    `投稿本文:\n${preview.body}`,
  ].join('\n\n');
}

export function buildKakuyomuPreview({ storyText = '', settings = {} } = {}) {
  const body = stripStoryMakerFooter(storyText);
  const title = extractStoryTitle(body, settings);
  const submissionBody = cleanSubmissionBodyArtifacts(dropTitleLine(body, title));
  const genre = suggestKakuyomuGenre(settings);
  const selfRatings = detectSelfRatings(body);
  const tags = createKakuyomuTags({ settings, kakuyomuGenre: genre });
  const chapters = splitKakuyomuBodyChapters(submissionBody);
  const preview = {
    title,
    workStatus: inferWorkStatus(settings),
    workType: 'オリジナル小説',
    genre,
    catchCopy: buildCatchCopy(body, title, settings),
    introduction: buildIntroduction(body, title, settings),
    selfRatings,
    tags,
    aiUseTag: AI_USE_TAG,
    contest: '応募しない（応募する場合は対象コンテストを選択）',
    userEvent: '参加しない（必要な自主企画だけ選択）',
    collection: '未設定',
    imageColor: chooseImageColor(genre),
    adDisplay: '広告を表示する',
    reservedPublish: '表示する',
    updateSchedule: '設定しない',
    body: submissionBody,
    chapters,
  };
  preview.copyAll = formatKakuyomuPreview(preview);
  return preview;
}

export function splitKakuyomuBodyChapters(body = '') {
  const text = stripStoryMakerFooter(body);
  const lines = normalizeText(text).split('\n');
  const headingPattern = CHAPTER_HEADING_PATTERN;
  const chapters = [];
  const preface = [];
  let current = null;

  for (const line of lines) {
    if (headingPattern.test(line.trim())) {
      if (current) chapters.push(current);
      const label = compactSpaces(line.replace(/^[#\s\u3000【]+|[】\s\u3000]+$/gu, ''));
      current = {
        label: limitJapaneseChars(label || `第${chapters.length + 1}章`, 32),
        lines: [],
      };
      preface.length = 0;
    } else if (current) {
      current.lines.push(line);
    } else if (line.trim()) {
      preface.push(line);
    }
  }
  if (current) chapters.push(current);
  return chapters
    .map((chapter, index) => ({
      label: chapter.label || `第${index + 1}章`,
      body: chapter.lines.join('\n').trim(),
    }))
    .filter(chapter => charLength(chapter.body) >= 40);
}

function readActiveChipText(selector) {
  return document.querySelector(selector)?.textContent?.trim() || '';
}

function readInputValue(id) {
  return document.getElementById(id)?.value?.trim() || '';
}

function readAxisValue(axis) {
  return (
    readInputValue(`${axis}-custom`)
    || readActiveChipText(`#${axis}-sub-chips .chip.active`)
    || readActiveChipText(`#${axis}-cat-chips .chip.active`)
  );
}

function readSettingsFromDom() {
  return {
    modeLabel: readInputValue('mode-custom') || readActiveChipText('#mode-chips .chip.active'),
    theme: readAxisValue('theme'),
    genre: readAxisValue('genre'),
    worldview: readAxisValue('worldview'),
    target: readAxisValue('target'),
    era: readAxisValue('era'),
    ending: readAxisValue('ending'),
    narration: readAxisValue('narr'),
  };
}

const COPY_BUTTON_LABELS = {
  all: 'Sao chép tất cả',
  tags: 'Sao chép danh sách thẻ',
  body: 'Sao chép toàn văn',
  chapterTitle: 'Sao chép tiêu đề chương',
  chapterBody: 'Sao chép nội dung',
};

const COPY_BUTTON_TITLES = {
  all: 'Sao chép toàn bộ mục đề xuất trong bản xem trước',
  tags: 'Sao chép các thẻ đề xuất để dán vào ô thẻ',
  body: 'Sao chép toàn bộ nội dung đăng bài',
  chapterTitle: 'Sao chép tiêu đề chương này',
  chapterBody: 'Sao chép riêng nội dung chương này',
};

function renderCopyButton(kind, options = {}) {
  const label = options.label || COPY_BUTTON_LABELS[kind] || 'Sao chép';
  const title = options.title || COPY_BUTTON_TITLES[kind] || `Sao chép ${label}`;
  const className = options.className ? ` ${options.className}` : '';
  const index = options.index === undefined ? '' : ` data-copy-index="${Ce(String(options.index))}"`;
  return `<button type="button" class="btn-secondary kakuyomu-copy-btn${className}" data-copy-kind="${Ce(kind)}"${index} title="${Ce(title)}" aria-label="${Ce(title)}">${Ce(label)}</button>`;
}

function renderRow({ label, value, kind, note = '', multiline = false, contentHtml = '', hideAction = false }) {
  const valueClass = multiline ? 'kakuyomu-preview-value is-multiline' : 'kakuyomu-preview-value';
  const body = contentHtml || `<div class="${valueClass}">${Ce(getVietnameseLabel(value))}</div>`;
  const noteHtml = note ? `<div class="kakuyomu-preview-note">${Ce(note)}</div>` : '';
  const actionHtml = hideAction ? '' : renderCopyButton(kind);
  return `
    <div class="kakuyomu-preview-row">
      <div class="kakuyomu-preview-label">${Ce(label)}</div>
      <div class="kakuyomu-preview-content">${body}${noteHtml}</div>
      <div class="kakuyomu-preview-actions">${actionHtml}</div>
    </div>
  `;
}

function renderTags(preview) {
  const tags = preview.tags.map((tag, index) => `
    <span class="kakuyomu-tag-item">
      <span class="kakuyomu-tag">${Ce(tag)}</span>
      ${renderCopyButton('tag', {
        label: 'Sao chép',
        title: `Sao chép ${tag}`,
        index,
        className: 'kakuyomu-tag-copy',
      })}
    </span>
  `).join('');
  return renderRow({
    label: 'Thẻ',
    kind: 'tags',
    note: 'Tối đa 8 thẻ, mỗi thẻ không quá 20 ký tự. Tác giả tự điều chỉnh thẻ AI theo tình trạng sử dụng AI.',
    hideAction: true,
    contentHtml: `<div class="kakuyomu-tag-list">${tags}</div>`,
  });
}

function renderSelfRatings(preview) {
  const value = preview.selfRatings.length ? preview.selfRatings.join(' / ') : '該当なし推奨';
  return renderRow({
    label: 'Tự phân loại độ tuổi',
    value,
    kind: 'selfRatings',
  });
}

function renderImageColor(preview) {
  return renderRow({
    label: 'Màu hình ảnh',
    kind: 'imageColor',
    value: `${preview.imageColor.label} (${preview.imageColor.hex})`,
    contentHtml: `
      <div class="kakuyomu-color-value">
        <span class="kakuyomu-color-swatch" style="background:${Ce(preview.imageColor.hex)}"></span>
        <span>${Ce(preview.imageColor.label)} (${Ce(preview.imageColor.hex)})</span>
      </div>
    `,
  });
}

function renderBodySection({ title, meta, copyKind, copyIndex, body, className = '', actionHtml = '' }) {
  const actions = actionHtml || renderCopyButton(copyKind, {
    index: copyIndex,
    className: copyKind === 'chapterBody' ? 'kakuyomu-chapter-copy' : '',
  });
  return `
    <section class="kakuyomu-body-block${className ? ` ${className}` : ''}">
      <div class="kakuyomu-body-block-head">
        <div>
          <div class="kakuyomu-body-block-title">${Ce(title)}</div>
          <div class="kakuyomu-body-block-meta">${Ce(meta)}</div>
        </div>
        <div class="kakuyomu-body-block-actions">${actions}</div>
      </div>
      <pre class="kakuyomu-body-preview${copyKind === 'chapterBody' ? ' kakuyomu-chapter-preview' : ''}">${Ce(body)}</pre>
    </section>
  `;
}

function renderBodySections(preview) {
  const fullBody = renderBodySection({
    title: 'Xem toàn văn',
    meta: `${charLength(preview.body)} ký tự`,
    copyKind: 'body',
    body: preview.body,
  });
  const chapters = preview.chapters?.length
    ? `
      <div class="kakuyomu-chapter-visible-list" aria-label="Hiển thị nội dung theo chương">
        ${preview.chapters.map((chapter, index) => renderBodySection({
          title: chapter.label,
          meta: `${charLength(chapter.body)} ký tự`,
          copyKind: 'chapterBody',
          copyIndex: index,
          body: chapter.body,
          className: 'kakuyomu-chapter-block',
          actionHtml: [
            renderCopyButton('chapterTitle', {
              label: 'Sao chép tiêu đề chương',
              title: `Sao chép ${chapter.label}`,
              index,
              className: 'kakuyomu-chapter-title-copy',
            }),
            renderCopyButton('chapterBody', {
              label: 'Sao chép nội dung',
              title: `Sao chép riêng nội dung ${chapter.label}`,
              index,
              className: 'kakuyomu-chapter-copy',
            }),
          ].join(''),
        })).join('')}
      </div>
    `
    : '';
  return `<div class="kakuyomu-body-sections">${fullBody}${chapters}</div>`;
}

export function renderKakuyomuPreview(preview) {
  return `
    <div class="kakuyomu-preview-titlebar">
      <div>
        <div class="kakuyomu-preview-kicker">Xem trước biểu mẫu Kakuyomu</div>
        <div class="kakuyomu-preview-name">${Ce(preview.title)}</div>
      </div>
      <span class="kakuyomu-preview-count">${charLength(preview.catchCopy)} / ${MAX_CATCH_COPY_CHARS} ký tự</span>
    </div>
    ${renderRow({ label: 'Tiêu đề truyện', value: preview.title, kind: 'title' })}
    ${renderRow({ label: 'Trạng thái đăng nhiều kỳ', value: preview.workStatus, kind: 'workStatus' })}
    ${renderRow({ label: 'Loại', value: preview.workType, kind: 'workType' })}
    ${renderRow({ label: 'Thể loại', value: preview.genre, kind: 'genre' })}
    ${renderRow({ label: 'Câu giới thiệu', value: preview.catchCopy, kind: 'catchCopy', note: 'Tối đa 35 ký tự' })}
    ${renderRow({ label: 'Giới thiệu', value: preview.introduction, kind: 'introduction', multiline: true })}
    ${renderSelfRatings(preview)}
    ${renderTags(preview)}
    ${renderRow({ label: 'Cuộc thi', value: preview.contest, kind: 'contest' })}
    ${renderRow({ label: 'Dự án cá nhân', value: preview.userEvent, kind: 'userEvent' })}
    ${renderRow({ label: 'Bộ sưu tập', value: preview.collection, kind: 'collection' })}
    ${renderImageColor(preview)}
    ${renderRow({ label: 'Hiển thị quảng cáo', value: preview.adDisplay, kind: 'adDisplay' })}
    ${renderRow({ label: 'Thời gian công khai bài đã hẹn', value: preview.reservedPublish, kind: 'reservedPublish' })}
    ${renderRow({ label: 'Lịch cập nhật', value: preview.updateSchedule, kind: 'updateSchedule' })}
    ${renderRow({
      label: 'Nội dung đăng bài',
      kind: 'body',
      multiline: true,
      hideAction: true,
      contentHtml: renderBodySections(preview),
    })}
  `;
}

export function getKakuyomuCopyValue(preview, kind, options = {}) {
  if (kind === 'tag') {
    const index = Number(options.tagIndex);
    return Number.isInteger(index) ? preview.tags[index] || '' : '';
  }
  if (kind === 'chapterBody') {
    const index = Number(options.chapterIndex ?? options.tagIndex);
    return Number.isInteger(index) ? preview.chapters?.[index]?.body || '' : '';
  }
  if (kind === 'chapterTitle') {
    const index = Number(options.chapterIndex ?? options.tagIndex);
    return Number.isInteger(index) ? preview.chapters?.[index]?.label || '' : '';
  }
  const values = {
    all: preview.copyAll,
    title: preview.title,
    workStatus: preview.workStatus,
    workType: preview.workType,
    genre: preview.genre,
    catchCopy: preview.catchCopy,
    introduction: preview.introduction,
    selfRatings: preview.selfRatings.length ? preview.selfRatings.join(' / ') : '該当なし推奨',
    tags: preview.tags.join('\n'),
    aiUseTag: preview.aiUseTag,
    contest: preview.contest,
    userEvent: preview.userEvent,
    collection: preview.collection,
    imageColor: `${preview.imageColor.label} (${preview.imageColor.hex})`,
    adDisplay: preview.adDisplay,
    reservedPublish: preview.reservedPublish,
    updateSchedule: preview.updateSchedule,
    body: preview.body,
  };
  return values[kind] || '';
}

function restoreButtonText(button, originalText) {
  setTimeout(() => {
    button.textContent = originalText;
    button.classList.remove('is-copied');
  }, 1200);
}

async function copyText(value, button) {
  const text = String(value || '');
  if (!text) return;
  const originalText = button.textContent;
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.setAttribute('readonly', '');
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    textarea.remove();
  }
  button.textContent = 'Đã sao chép';
  button.classList.add('is-copied');
  restoreButtonText(button, originalText);
}

function createTxtFileName() {
  return buildStoryExportFileName('KakuyomuForm', 'txt');
}

function saveTextFile(value, filename, button) {
  const text = String(value || '');
  if (!text) return;
  const originalText = button.textContent;
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename || 'kakuyomu-form-preview.txt';
  anchor.style.display = 'none';
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
  button.textContent = 'Đã lưu';
  button.classList.add('is-copied');
  restoreButtonText(button, originalText);
}

function outputHasStory(outputEl) {
  if (!outputEl || outputEl.classList.contains('empty')) return false;
  return charLength(stripStoryMakerFooter(outputEl.innerText || outputEl.textContent || '')) >= 40;
}

function isStoryGenerationActive() {
  const settingsEl = document.getElementById('settings');
  const generateButton = document.getElementById('btn-generate');
  const outputEl = document.getElementById('output');
  const buttonText = generateButton?.textContent || '';
  const outputText = (outputEl?.innerText || outputEl?.textContent || '').trim();
  return Boolean(
    settingsEl?.classList.contains('generating')
    || (
      generateButton?.disabled
      && /思考中|生成中|構築中|受信中|ライブ表示|API/i.test(buttonText)
    )
    || (
      generateButton?.disabled
      && /^(AIの思考を待っています|AIが考えています|受信待機中)/u.test(outputText)
    )
  );
}

export function installKakuyomuAssist() {
  const outputEl = document.getElementById('output');
  const rootEl = document.getElementById('kakuyomu-assist');
  const checkbox = document.getElementById('kakuyomu-assist-enable');
  const bodyEl = document.getElementById('kakuyomu-assist-body');
  const previewEl = document.getElementById('kakuyomu-form-preview');
  const statusEl = document.getElementById('kakuyomu-assist-status');
  if (!outputEl || !checkbox || !bodyEl || !previewEl || !statusEl) return;

  let lastPreview = null;
  let queued = false;
  let busy = false;

  const setCopyControlsDisabled = disabled => {
    bodyEl.querySelectorAll('.kakuyomu-copy-btn, .kakuyomu-save-btn').forEach(button => {
      button.disabled = Boolean(disabled);
    });
  };

  const applyLockedUi = (value, message = 'Cập nhật nội dung mới nhất sau khi xử lý xong') => {
    const locked = Boolean(value);
    rootEl?.classList.toggle('is-busy', locked);
    rootEl?.setAttribute('aria-busy', locked ? 'true' : 'false');
    checkbox.disabled = locked || !outputHasStory(outputEl);
    setCopyControlsDisabled(locked);
    if (locked) {
      statusEl.textContent = message;
    }
  };

  const setBusy = (value, message = '処理完了後に最新内容へ更新') => {
    busy = Boolean(value);
    applyLockedUi(busy, message);
  };

  const refresh = () => {
    queued = false;
    const generationActive = isStoryGenerationActive();
    if (busy || generationActive) {
      applyLockedUi(true, generationActive ? 'Cập nhật nội dung mới nhất sau khi tạo xong' : 'Cập nhật nội dung mới nhất sau khi xử lý xong');
      return;
    }
    applyLockedUi(false);
    const enabled = checkbox.checked;
    const canPreview = outputHasStory(outputEl);
    checkbox.disabled = !canPreview;
    bodyEl.classList.toggle('hidden', !enabled || !canPreview);
    if (!canPreview) {
      lastPreview = null;
      statusEl.textContent = 'Hiển thị sau khi có kết quả';
      previewEl.innerHTML = '';
      setCopyControlsDisabled(true);
      return;
    }
    const storyText = outputEl.innerText || outputEl.textContent || '';
    lastPreview = buildKakuyomuPreview({
      storyText,
      settings: readSettingsFromDom(),
    });
    statusEl.textContent = enabled
      ? `Đang hiển thị: ${lastPreview.tags.length} thẻ đề xuất`
      : 'Đánh dấu để hiển thị';
    if (enabled) previewEl.innerHTML = renderKakuyomuPreview(lastPreview);
    setCopyControlsDisabled(!enabled);
  };

  const scheduleRefresh = () => {
    if (queued) return;
    queued = true;
    window.requestAnimationFrame(refresh);
  };

  checkbox.checked = false;
  checkbox.addEventListener('change', refresh);
  window.addEventListener('story-maker:kakuyomu-busy', event => {
    setBusy(event.detail?.busy);
    if (!busy) scheduleRefresh();
  });
  window.addEventListener('story-maker:kakuyomu-refresh', scheduleRefresh);

  bodyEl.addEventListener('click', event => {
    const saveButton = event.target?.closest?.('.kakuyomu-save-btn');
    if (saveButton && !saveButton.disabled && !busy && lastPreview) {
      saveTextFile(lastPreview.copyAll, createTxtFileName(lastPreview), saveButton);
      return;
    }
    const button = event.target?.closest?.('.kakuyomu-copy-btn');
    if (!button || button.disabled || busy || !lastPreview) return;
    copyText(getKakuyomuCopyValue(lastPreview, button.dataset.copyKind, {
      tagIndex: button.dataset.copyIndex,
      chapterIndex: button.dataset.copyIndex,
    }), button);
  });

  ['mode', 'theme', 'genre', 'worldview', 'target', 'era', 'ending', 'narr'].forEach(axis => {
    document.getElementById(`${axis}-custom`)?.addEventListener('input', scheduleRefresh);
    document.getElementById(`${axis}-custom`)?.addEventListener('change', scheduleRefresh);
  });
  document.addEventListener('click', event => {
    if (event.target?.closest?.('.chip, .btn-all-random, #btn-rand-mode')) {
      setTimeout(scheduleRefresh, 0);
    }
  });

  const observer = new MutationObserver(scheduleRefresh);
  observer.observe(outputEl, {
    childList: true,
    characterData: true,
    subtree: true,
    attributes: true,
    attributeFilter: ['class'],
  });
  const settingsEl = document.getElementById('settings');
  const generateButton = document.getElementById('btn-generate');
  if (settingsEl) {
    observer.observe(settingsEl, {
      attributes: true,
      attributeFilter: ['class'],
    });
  }
  if (generateButton) {
    observer.observe(generateButton, {
      childList: true,
      characterData: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['disabled', 'class'],
    });
  }
  refresh();
}
