const VIETNAMESE_LABELS = {
  '4コマ漫画風': 'Truyện tranh 4 khung',
  'AI 4koma シナリオ連携（STEP2）': 'Kịch bản AI 4koma (STEP2)',
  'ショート': 'Truyện cực ngắn',
  'ショート（1500字～）': 'Truyện cực ngắn (từ 1.500 chữ)',
  '小説': 'Tiểu thuyết',
  '短編小説（4500字～）': 'Truyện ngắn (từ 4.500 chữ)',
  '中編小説（5500字～）': 'Truyện vừa (từ 5.500 chữ)',
  '長編（10000字～）': 'Truyện dài (từ 10.000 chữ)',
  '長編小説(数万字/全章＋指示書)': 'Tiểu thuyết dài (toàn bộ chương + hướng dẫn)',
  '脚本/台本': 'Kịch bản / Lời thoại',
  'ストーリー漫画': 'Truyện tranh dài tập',
  'エッセイ': 'Tản văn',
  '詩・ポエム': 'Thơ',
  '童話/絵本': 'Truyện cổ tích / Sách tranh',
  '手紙/書簡体': 'Thư từ',
  '日記/独白体': 'Nhật ký / Độc thoại',
  'ドキュメンタリー': 'Tư liệu',
  'ラジオドラマ': 'Kịch phát thanh',
  '日常・生活': 'Đời sống thường nhật',
  'コンビニ': 'Cửa hàng tiện lợi',
  '通学路': 'Đường đến trường',
  'お昼休み': 'Giờ nghỉ trưa',
  '雨の日': 'Ngày mưa',
  '洗濯物': 'Quần áo giặt',
  '引っ越し': 'Chuyển nhà',
  '忘れ物': 'Đồ bỏ quên',
  '遅刻': 'Đi muộn',
  '卒業式': 'Lễ tốt nghiệp',
  '初デート': 'Buổi hẹn đầu',
  'ファンタジー': 'Kỳ ảo',
  '魔法学校': 'Trường phép thuật',
  '異世界転生': 'Chuyển sinh sang thế giới khác',
  '勇者の休日': 'Ngày nghỉ của dũng sĩ',
  'ドラゴンの涙': 'Nước mắt rồng',
  '魔王の孤独': 'Nỗi cô độc của ma vương',
  '精霊の森': 'Rừng tinh linh',
  '古代遺跡': 'Di tích cổ đại',
  '聖剣伝説': 'Truyền thuyết thánh kiếm',
  '妖精の国': 'Vương quốc tiên',
  '封印された塔': 'Tòa tháp bị phong ấn',
  'SF・近未来': 'Khoa học viễn tưởng · Tương lai gần',
  '月面都市': 'Thành phố trên Mặt Trăng',
  'AIとの恋': 'Tình yêu với AI',
  'タイムトラベル': 'Du hành thời gian',
  '廃墟のロボット': 'Robot giữa phế tích',
  '宇宙ステーション': 'Trạm không gian',
  'クローン人間': 'Con người nhân bản',
  '火星移住': 'Di cư lên Sao Hỏa',
  '量子コンピュータ': 'Máy tính lượng tử',
  '仮想現実': 'Thực tế ảo',
  'ディストピア': 'Thế giới phản địa đàng',
  'ミステリー': 'Bí ẩn',
  '孤島の一軒家': 'Ngôi nhà cô độc trên đảo',
  '謎の暗号': 'Mật mã bí ẩn',
  '消えた記憶': 'Ký ức biến mất',
  '深夜の電話': 'Cuộc gọi lúc nửa đêm',
  '密室殺人': 'Án mạng phòng kín',
  '消えた遺産': 'Di sản biến mất',
  '最後の手紙': 'Lá thư cuối cùng',
  '二重人格': 'Đa nhân cách',
  '偽のアリバイ': 'Ngoại phạm giả',
  '暗号日記': 'Nhật ký mật mã',
  '恋愛・青春': 'Tình yêu · Tuổi trẻ',
  '屋上の秘密': 'Bí mật trên sân thượng',
  '幼馴染': 'Bạn thuở nhỏ',
  '転校生': 'Học sinh chuyển trường',
  '夏祭り': 'Lễ hội mùa hè',
  '文化祭': 'Lễ hội văn hóa',
  '先輩後輩': 'Tiền bối · Hậu bối',
  '片想い': 'Tình yêu đơn phương',
  '遠距離': 'Tình yêu xa',
  '再会': 'Tái ngộ',
  '告白': 'Tỏ tình',
  '歴史・時代劇': 'Lịch sử · Cổ trang',
  '刀鍛冶': 'Thợ rèn kiếm',
  '忍者の末裔': 'Hậu duệ ninja',
  '剣豪': 'Kiếm khách',
  '城下町': 'Thị trấn dưới chân thành',
  '幕末の志士': 'Chí sĩ cuối thời Mạc phủ',
  '大航海時代': 'Thời đại hàng hải',
  '古代ローマ': 'La Mã cổ đại',
  '戦国武将': 'Võ tướng thời Chiến Quốc',
  '平安貴族': 'Quý tộc thời Heian',
  '明治の文豪': 'Văn hào thời Minh Trị',
  'ホラー・怪奇': 'Kinh dị · Quái dị',
  '廃病院': 'Bệnh viện bỏ hoang',
  '心霊写真': 'Ảnh ma',
  '呪いの人形': 'Búp bê bị nguyền',
  '鏡の中': 'Trong gương',
  '都市伝説': 'Truyền thuyết đô thị',
  '深夜の学校': 'Ngôi trường lúc nửa đêm',
  '禁忌の扉': 'Cánh cửa cấm kỵ',
  '異界への門': 'Cánh cổng sang dị giới',
  'ドッペルゲンガー': 'Kẻ song trùng',
  '赤い部屋': 'Căn phòng đỏ',
  'コメディ': 'Hài hước',
  '爆笑': 'Gây cười lớn',
  'ドタバタ': 'Hỗn loạn vui nhộn',
  'ギャグ': 'Gag',
  '勘違い': 'Hiểu lầm',
  'パロディ': 'Nhại',
  'ツッコミ不在': 'Không ai bắt lỗi',
  '天然ボケ': 'Ngây ngô hài hước',
  'シュールギャグ': 'Hài siêu thực',
  'シリアス': 'Nghiêm túc',
  '復讐': 'Báo thù',
  '挫折': 'Thất bại',
  '重い過去': 'Quá khứ nặng nề',
  '葛藤': 'Giằng xé',
  '裏切り': 'Phản bội',
  '贖罪': 'Chuộc lỗi',
  '決断': 'Quyết định',
  '犠牲': 'Hy sinh',
  '恋愛': 'Tình yêu',
  '純愛': 'Tình yêu thuần khiết',
  '三角関係': 'Tình tay ba',
  '失恋': 'Thất tình',
  'ラブコメ': 'Hài lãng mạn',
  '切ない恋': 'Tình yêu day dứt',
  '禁断の恋': 'Tình yêu cấm kỵ',
  '運命の出会い': 'Cuộc gặp định mệnh',
  'ホラー': 'Kinh dị',
  '怪談': 'Chuyện ma',
  '心霊現象': 'Hiện tượng tâm linh',
  'サイコホラー': 'Kinh dị tâm lý',
  'ゴシックホラー': 'Kinh dị Gothic',
  'モダンホラー': 'Kinh dị hiện đại',
  '因果応報': 'Nhân quả báo ứng',
  'アクション': 'Hành động',
  'バトル': 'Đối đầu',
  '冒険': 'Phiêu lưu',
  '追跡劇': 'Màn truy đuổi',
  '脱出': 'Đào thoát',
  '潜入': 'Xâm nhập',
  '決闘': 'Đấu tay đôi',
  'サバイバル': 'Sinh tồn',
  'ヒューマンドラマ': 'Tâm lý xã hội',
  '家族': 'Gia đình',
  '友情': 'Tình bạn',
  '成長': 'Trưởng thành',
  '別れ': 'Chia ly',
  '和解': 'Hòa giải',
  '再生': 'Tái sinh',
  '絆': 'Gắn kết',
  'サスペンス': 'Hồi hộp',
  '犯人探し': 'Truy tìm hung thủ',
  '陰謀': 'Âm mưu',
  '心理戦': 'Đấu trí',
  'スパイ': 'Gián điệp',
  '二転三転': 'Nhiều lần đảo chiều',
  'タイムリミット': 'Giới hạn thời gian',
  '現代日本': 'Nhật Bản hiện đại',
  '東京': 'Tokyo',
  '地方都市': 'Thành phố địa phương',
  '田舎の村': 'Làng quê',
  '学校': 'Trường học',
  'オフィス': 'Văn phòng',
  '商店街': 'Phố mua sắm',
  '団地': 'Khu tập thể',
  '離島': 'Đảo xa',
  '現代海外': 'Nước ngoài hiện đại',
  'ニューヨーク': 'New York',
  'ロンドン': 'London',
  'パリ': 'Paris',
  '上海': 'Thượng Hải',
  'ドバイ': 'Dubai',
  'シドニー': 'Sydney',
  'ラテンアメリカ': 'Mỹ Latinh',
  'ハイファンタジー': 'Kỳ ảo cao cấp',
  '中世ヨーロッパ風': 'Phong cách châu Âu trung cổ',
  '王道': 'Chính thống',
  'エルフの森': 'Rừng elf',
  'ドワーフの鉱山': 'Mỏ người lùn',
  '魔法帝国': 'Đế quốc phép thuật',
  '竜の巣': 'Hang rồng',
  '空中都市': 'Thành phố trên không',
  'ローファンタジー': 'Kỳ ảo đô thị',
  '現代＋魔法': 'Hiện đại + phép thuật',
  '裏社会の魔術師': 'Pháp sư thế giới ngầm',
  '能力バトル': 'Đối đầu năng lực',
  '異能の学園': 'Học viện dị năng',
  'サイバーパンク': 'Cyberpunk',
  'ネオン街': 'Phố đèn neon',
  'スラム': 'Khu ổ chuột',
  '電脳世界': 'Thế giới điện não',
  '巨大企業支配': 'Tập đoàn khổng lồ thống trị',
  'アンドロイド社会': 'Xã hội android',
  '和風・アジア': 'Phong vị Nhật · châu Á',
  '京都': 'Kyoto',
  '神社仏閣': 'Đền chùa',
  '武士の世界': 'Thế giới võ sĩ',
  '中華風宮廷': 'Cung đình phong cách Trung Hoa',
  '妖怪の里': 'Làng yêu quái',
  'ポストアポカリプス': 'Hậu tận thế',
  '荒廃都市': 'Thành phố hoang tàn',
  '砂漠世界': 'Thế giới sa mạc',
  '水没都市': 'Thành phố chìm dưới nước',
  '核の冬': 'Mùa đông hạt nhân',
  '文明崩壊後': 'Sau khi nền văn minh sụp đổ',
  '全年齢': 'Mọi lứa tuổi',
  '子供向け': 'Dành cho trẻ em',
  'ファミリー': 'Gia đình',
  '誰でも楽しめる': 'Ai cũng có thể thưởng thức',
  '教育的': 'Mang tính giáo dục',
  '若者向け': 'Dành cho người trẻ',
  '中高生向け': 'Dành cho học sinh trung học',
  '大学生向け': 'Dành cho sinh viên',
  'ライトノベル風': 'Phong cách light novel',
  'SNS世代向け': 'Dành cho thế hệ mạng xã hội',
  'Z世代向け': 'Dành cho Gen Z',
  '大人向け': 'Dành cho người lớn',
  '仕事帰りに読む': 'Đọc sau giờ làm',
  '深夜番組風': 'Phong cách chương trình đêm khuya',
  '文学的': 'Văn chương',
  'ビジネスマン向け': 'Dành cho người đi làm',
  '知的好奇心旺盛な人向け': 'Dành cho người ham hiểu biết',
  '特定層向け': 'Dành cho nhóm độc giả cụ thể',
  '男性向け': 'Dành cho nam giới',
  '女性向け': 'Dành cho nữ giới',
  'ファン向け': 'Dành cho người hâm mộ',
  'オタク文化に親しい人向け': 'Dành cho người am hiểu văn hóa otaku',
  'シニア向け': 'Dành cho người cao tuổi',
  '用途別': 'Theo mục đích sử dụng',
  '読み聞かせ用': 'Dùng để đọc cho nghe',
  'プレゼン用': 'Dùng cho thuyết trình',
  '朗読用': 'Dùng để đọc diễn cảm',
  'BGM付き朗読向け': 'Dành cho đọc diễn cảm kèm nhạc nền',
  '現代': 'Hiện đại',
  '2020年代': 'Thập niên 2020',
  '2010年代': 'Thập niên 2010',
  '2000年代': 'Thập niên 2000',
  '1990年代': 'Thập niên 1990',
  '昭和末期': 'Cuối thời Showa',
  '近代': 'Cận đại',
  '明治時代': 'Thời Minh Trị',
  '大正時代': 'Thời Taisho',
  '昭和初期': 'Đầu thời Showa',
  '戦後復興期': 'Thời kỳ phục hưng sau chiến tranh',
  '中世・近世': 'Trung cổ · cận thế',
  '戦国時代': 'Thời Chiến Quốc',
  '江戸時代': 'Thời Edo',
  '平安時代': 'Thời Heian',
  '鎌倉時代': 'Thời Kamakura',
  '室町時代': 'Thời Muromachi',
  '古代': 'Cổ đại',
  '古代日本': 'Nhật Bản cổ đại',
  '古代エジプト': 'Ai Cập cổ đại',
  '古代ギリシャ': 'Hy Lạp cổ đại',
  '古代中国': 'Trung Hoa cổ đại',
  '未来': 'Tương lai',
  '近未来(50年後)': 'Tương lai gần (50 năm sau)',
  '100年後': '100 năm sau',
  '遠い未来(1000年後)': 'Tương lai xa (1.000 năm sau)',
  '文明崩壊後の未来': 'Tương lai sau khi văn minh sụp đổ',
  '架空': 'Hư cấu',
  'パラレルワールド': 'Thế giới song song',
  'ループする時間': 'Thời gian lặp vòng',
  '時間が止まった世界': 'Thế giới nơi thời gian dừng lại',
  '複数時代が混在': 'Nhiều thời đại đan xen',
  'ハッピーエンド': 'Kết thúc có hậu',
  '大団円': 'Đại đoàn viên',
  '救いがある': 'Có sự cứu rỗi',
  '夢が叶う': 'Ước mơ thành hiện thực',
  '大逆転勝利': 'Chiến thắng lội ngược dòng',
  '愛の成就': 'Tình yêu viên mãn',
  'バッドエンド': 'Kết thúc buồn',
  '切ない': 'Day dứt',
  '救いがない': 'Không có lối thoát',
  '後味悪い': 'Dư vị cay đắng',
  '破滅': 'Diệt vong',
  '取り返しのつかない選択': 'Lựa chọn không thể cứu vãn',
  'ビターエンド': 'Kết thúc đắng',
  'ほろ苦い': 'Đắng dịu',
  '代償を伴う勝利': 'Chiến thắng phải trả giá',
  '成長と引き換えの喪失': 'Mất mát để đổi lấy trưởng thành',
  '痛みを伴う真実': 'Sự thật đi cùng đau đớn',
  'サプライズ': 'Bất ngờ',
  'どんでん返し': 'Cú twist',
  '叙述トリック': 'Thủ pháp đánh lừa tự sự',
  '真犯人の正体': 'Thân phận hung thủ thật sự',
  '伏線回収の衝撃': 'Cú sốc khi các tình tiết gài được giải đáp',
  'オープンエンド': 'Kết thúc mở',
  '読者に委ねる': 'Để độc giả tự quyết định',
  '余韻を残す': 'Để lại dư âm',
  '続編を匂わせる': 'Gợi mở phần tiếp theo',
  '解釈が分かれる': 'Nhiều cách diễn giải',
  'その他': 'Khác',
  '夢オチ': 'Hóa ra là một giấc mơ',
  'ループ': 'Vòng lặp',
  'メタ的オチ': 'Kết thúc siêu tự sự',
  'シュールな結末': 'Kết thúc siêu thực',
  '第四の壁破壊': 'Phá vỡ bức tường thứ tư',
  '一人称': 'Ngôi thứ nhất',
  '「僕」の視点': 'Góc nhìn “tôi” nam',
  '「私」の独白': 'Độc thoại “tôi”',
  '「俺」のハードボイルド': 'Hard-boiled qua góc nhìn “ta”',
  '信頼できない語り手': 'Người kể chuyện không đáng tin',
  '回想録形式': 'Dạng hồi ký',
  '三人称': 'Ngôi thứ ba',
  '神の視点': 'Góc nhìn toàn tri',
  '俯瞰的': 'Góc nhìn bao quát',
  '特定キャラに寄り添う': 'Bám sát một nhân vật',
  '群像劇（視点切替）': 'Truyện đa nhân vật (đổi góc nhìn)',
  '特殊': 'Đặc biệt',
  '二人称（あなた）': 'Ngôi thứ hai (“bạn”)',
  '手紙・書簡形式': 'Dạng thư từ',
  'インタビュー形式': 'Dạng phỏng vấn',
  '日記体': 'Dạng nhật ký',
  'モノローグ劇': 'Kịch độc thoại',
  '実況中継風': 'Phong cách tường thuật trực tiếp',
  '主人公': 'Nhân vật chính',
  'ライバル': 'Đối thủ',
  '相棒': 'Cộng sự',
  'ヒロイン': 'Nữ chính',
  '悪役': 'Phản diện',
  '師匠': 'Sư phụ',
  'モブ': 'Nhân vật quần chúng',
  '謎の人物': 'Nhân vật bí ẩn',
  '語り部': 'Người kể chuyện',
  'トリックスター': 'Kẻ khuấy đảo',
  '観測者': 'Người quan sát',
  '犠牲者': 'Nạn nhân',
  '裏切り者': 'Kẻ phản bội',
  '調停者': 'Người hòa giải',
  '復讐者': 'Kẻ báo thù',
  '守護者': 'Người bảo hộ',
  '道化師': 'Chú hề',
  '黒幕': 'Kẻ chủ mưu',
  '熱血': 'Nhiệt huyết',
  '冷静沈着': 'Điềm tĩnh',
  'ツンデレ': 'Tsundere',
  'お人好し': 'Tốt bụng cả tin',
  'ミステリアス': 'Bí ẩn',
  '臆病': 'Nhút nhát',
  '自信家': 'Tự tin',
  'のんびり屋': 'Thong thả',
  '毒舌家': 'Miệng lưỡi cay độc',
  '天然': 'Ngây thơ',
  '楽天家': 'Lạc quan',
  '皮肉屋': 'Hay mỉa mai',
  '偏執的': 'Ám ảnh cực đoan',
  '世話焼き': 'Hay chăm lo',
  '無口': 'Ít nói',
  '二面性あり': 'Có hai mặt',
  '感情的': 'Giàu cảm xúc',
  '理知的': 'Lý trí',
  '男性': 'Nam',
  '女性': 'Nữ',
  '無性': 'Phi giới tính',
  '回答無し': 'Không trả lời',
  '未選択': 'Chưa chọn',
  'カテゴリ選択': 'Chọn danh mục',
  'キャラ文芸': 'Văn học nhân vật',
  'ライト文芸': 'Văn học nhẹ nhàng',
  '大衆娯楽': 'Giải trí đại chúng',
  '経済・企業': 'Kinh tế · doanh nghiệp',
  '歴史・時代': 'Lịch sử · thời đại',
  '児童書・童話': 'Sách thiếu nhi · cổ tích',
  '絵本': 'Sách tranh',
  'エッセイ・ノンフィクション': 'Tản văn · phi hư cấu',
  'ショートショート': 'Truyện cực ngắn',
  '短編': 'Truyện ngắn',
  '長編': 'Truyện dài',
  '連載中': 'Đang đăng nhiều kỳ',
  '完結': 'Hoàn thành',
  'なし': 'Không',
  '設定しない': 'Không thiết lập',
  '新しい章を追加する': 'Thêm chương mới',
  '該当なし推奨': 'Khuyến nghị không áp dụng',
  '男性向け': 'Dành cho nam giới',
  '女性向け': 'Dành cho nữ giới',
  'R15': 'R15',
  'R18': 'R18',
};

function getVietnameseLabel(value) {
  const key = String(value ?? '');
  return VIETNAMESE_LABELS[key] || key;
}

export { VIETNAMESE_LABELS, getVietnameseLabel };
